# Generated by Django 2.2 on 2020-12-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_remove_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
